version: '3.5'
services:
  backend-app:
    build:
      context: $PWD/app/server
      args:
      - PARAMETER_1=production
      - PARAMETER_2=52.192.233.244
    image: centos/golang-app-prd
    container_name: expenses-golang-app
    tty: true
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
  frontend-app:
    build:
      context: $PWD/app/frontend
      args:
      - PARAMETER_1=production
    image: centos/angular-app-prd
    container_name: expenses-angular-app
    tty: true
    ports:
    - 80:80
    environment:
    - TZ=Asia/Tokyo
  db:
    image: project-first/mysql
    container_name: expenses-db
    ports:
    - 3306:3306
    volumes:
    - $PWD/mysql/volumes:/var/lib/mysql
    - $PWD/mysql/config:/etc/mysql/conf.d
