version: '2'
services:
  app:
    image: centos/angular-typescript-tutorial
    container_name: expenses-app
    tty: true
    ports:
      - 4200:4200
      - 3000:3000
    volumes:
      - $PWD/app/frontend:/home/frontend
      - $PWD/app/server:/home/go/src/expenses
    environment:
      - TZ=Asia/Tokyo
    privileged: true
    command: /sbin/init
  db:
#    image: project-first/mysql
    image: project-first/mysql
    container_name: expenses-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - 3306:3306
    volumes:
    - $PWD/mysql/volumes:/var/lib/mysql
    - $PWD/mysql/config:/etc/mysql/conf.d
